spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    kafka:
      port: 29092
      host: localhost
      group-id: logist_service
      channels:
        route-events-channel:
          name: route_event_channel
        location-events-channel:
          name: location_event_channel

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  application:
    name: logist-service

  cloud:
    discovery:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://${services.registry.host}:${services.registry.port}/eureka/
  instance:
    prefer-ip-address: true

services:
  registry:
    host: localhost
    port: 8761

server:
  port: 8083