spring:
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      group-id: logist-service
      auto-offset-reset: earliest
    topics:
      route-event-topic:
        name: route_event_topic
      location-event-topic:
        name: location_event_topic

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: user
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml

  application:
    name: logist-service

  cloud:
    discovery:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://${services.registry.host}:${services.registry.port}/eureka/
  instance:
    prefer-ip-address: true

services:
  registry:
    host: localhost
    port: 8761
  portal:
    url:
      base: http://localhost:8082
      get-user-by-id: /user


server:
  port: 8083